spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yesg?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


springdoc:
  packages-to-scan: youresg.yesg
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui-yesg.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true